#!/bin/bash

# Define the root directory
ROOT_DIR="project"

# Create the main directories
mkdir -p $ROOT_DIR/{data/{raw,processed,external},R,notebooks,SQL,utils,visualization/{dashboards,reports},config,tests,logs,docker}

# Create placeholder files in each directory
touch $ROOT_DIR/data/raw/.gitkeep
touch $ROOT_DIR/data/processed/.gitkeep
touch $ROOT_DIR/data/external/.gitkeep

cat <<EOL > $ROOT_DIR/R/data_collection.R
# Script for data collection
EOL

cat <<EOL > $ROOT_DIR/R/data_cleaning.R
# Script for data cleaning
EOL

cat <<EOL > $ROOT_DIR/R/etl_pipeline.R
# Script to run the entire ETL pipeline
EOL

cat <<EOL > $ROOT_DIR/R/analysis.R
# Script for performing data analysis
EOL

cat <<EOL > $ROOT_DIR/notebooks/EDA.Rmd
---
title: "Exploratory Data Analysis"
output: html_notebook
---

# EDA
EOL

cat <<EOL > $ROOT_DIR/notebooks/data_cleaning.Rmd
---
title: "Data Cleaning"
output: html_notebook
---

# Data Cleaning
EOL

cat <<EOL > $ROOT_DIR/notebooks/model_building.Rmd
---
title: "Model Building"
output: html_notebook
---

# Model Building
EOL

cat <<EOL > $ROOT_DIR/SQL/create_tables.sql
-- SQL script for creating database tables
EOL

cat <<EOL > $ROOT_DIR/SQL/queries.sql
-- SQL queries used for analysis
EOL

cat <<EOL > $ROOT_DIR/SQL/transformations.sql
-- SQL scripts for transforming data within the database
EOL

cat <<EOL > $ROOT_DIR/utils/db_utils.R
# Utility functions for database operations
EOL

cat <<EOL > $ROOT_DIR/utils/data_utils.R
# Utility functions for data manipulation
EOL

cat <<EOL > $ROOT_DIR/utils/visualization_utils.R
# Utility functions for creating visualizations
EOL

touch $ROOT_DIR/visualization/dashboards/.gitkeep
touch $ROOT_DIR/visualization/reports/.gitkeep

cat <<EOL > $ROOT_DIR/config/.gitkeep
# Configuration files (e.g., database connection settings, API keys)
EOL

cat <<EOL > $ROOT_DIR/tests/.gitkeep
# Unit tests and integration tests
EOL

cat <<EOL > $ROOT_DIR/logs/.gitkeep
# Log files generated by scripts
EOL

cat <<EOL > $ROOT_DIR/docker/.gitkeep
# Docker-related files
EOL

cat <<EOL > $ROOT_DIR/README.md
# Project Overview
This project is designed to...

## Directory Structure
- **data/**: Contains raw, processed, and external data files.
- **R/**: R scripts for data collection, cleaning, ETL pipeline, and analysis.
- **notebooks/**: R Markdown notebooks for EDA, data cleaning, and model building.
- **SQL/**: SQL scripts for database operations.
- **utils/**: Utility functions for various tasks.
- **visualization/**: Dashboards and reports.
- **config/**: Configuration files.
- **tests/**: Unit tests and integration tests.
- **logs/**: Log files.
- **docker/**: Docker-related files.

## Setup Instructions
...
EOL

echo "Project structure created successfully."

